/** Emoji shown before amenity labels in pills, filters, and lists. */
export const DEFAULT_AMENITY_EMOJI = '✨';

export const AMENITY_EMOJIS: Record<string, string> = {
  ac: '❄️',
  'air conditioner': '❄️',
  'attached bathroom': '🚿',
  balcony: '🌅',
  'carrom board': '🎯',
  carrom: '🎯',
  carom: '🎯',
  'cloths dry stand': '👕',
  'dry stand': '👕',
  'coffee table': '☕',
  cots: '🛏️',
  cupboard: '🗄️',
  dth: '📡',
  'dining table & chair': '🍽️',
  'dinning table': '🍽️',
  'common dining area': '🍽️',
  foosball: '⚽',
  fridge: '🧊',
  geyser: '♨️',
  'house keeping': '🧹',
  housekeeping: '🧹',
  cleaning: '🧹',
  'daily house cleaning': '🧹',
  kitchen: '🍳',
  'basic kitchen': '🍳',
  'basic common kitchen': '🍳',
  kitchenette: '🍳',
  'fully equipped kitchenette': '🍳',
  lift: '🛗',
  elevator: '🛗',
  'mattress 5inch': '🛏️',
  'mattress 6inch': '🛏️',
  'mattress 8inch': '🛏️',
  'mattress queen 5inch': '🛏️',
  'mattress queen 6inch': '🛏️',
  'mattress queen 8inch': '🛏️',
  'twin mattress 5inch': '🛏️',
  'twin mattress 6inch': '🛏️',
  'twin mattress 8inch': '🛏️',
  'bed type queen 5x6': '🛏️',
  'twin 3x6': '🛏️',
  pillow: '🛌',
  ro: '🚰',
  'ro drinking water': '🚰',
  'side table': '🪑',
  'study table with chair': '📚',
  sofa: '🪑',
  'soft furnishing': '🛋️',
  'study table': '📚',
  tv: '📺',
  "65' led tv": '📺',
  '65" led tv': '📺',
  'table tennis': '🏓',
  'washing machine': '🫙',
  laundry: '🧺',
  'water cooler': '🧊',
  water: '💧',
  internet: '📶',
  wifi: '📶',
  food: '🍽️',
  security: '🔒',
  cctv: '📹',
  'cctv camera': '📹',
  gym: '💪',
  gas: '🔥',
  'gas induction': '🔥',
  'gas connection': '🔥',
  'power backup': '🔋',
  '24/7 power backup': '🔋',
  electricity: '⚡',
  microwave: '🥘',
  'covered parking': '🅿️',
  'un-covered parking': '🅿️',
  parking: '🅿️',
  'bar table': '🪑',
  'dart board': '🎯',
  dartboard: '🎯',
  hammok: '🏖️',
  hammock: '🏖️',
  library: '📚',
  'mini golf': '⛳',
  monopoly: '🎲',
  playstation: '🎮',
  uno: '🃏',
  'board games': '🎲',
  chess: '♟️',
  gardening: '🌿',
  'rooftop garden': '🌿',
  'shoe rack': '👟',
  'bio-metric': '🔐',
  'biometric access': '🔐',
  'community events': '🎉',
};
